# CI de Nivel 01 - Disparo manual a partir de 1 clique
# v6

name: "Execução Manual"

on:
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalacao do node  
      - name: Instalando Node
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      # instalacao do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalacao das dependencias
      - name: Instalando dependências
        run: yarn install
      
      # instalacao do playwright
      - name: Instalando Playwright
        run: npx playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e